# =============================
#!name = 🐾  Alight Motion 💞
#!desc = Module Alight Motion Premium  ~ Đã Fix lỗi by Khổng Mạnh Yên 👑
# Mở khoá Premium cho ứng dụng  Alight Motion Premium 
#!author= Mạnh Yên (Kthy) 💞
# 💬 Web: https://beacons.ai/o.oyen  
# 🫆 Tạo bởi: Khổng Mạnh Yên 🐥
#!version= 2.0
# =============================
[General]
bypass-system = true
skip-proxy = *.local, *.crashlytics.com
tun-excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12

[MITM]
hostname = api.revenuecat.com, buy.itunes.apple.com, us-central1-alight-creative.cloudfunctions.net

[Script]
http-response https://us-central1-alight-creative.cloudfunctions.net/getAccountStatusAndLicenses script-path=https://raw.githubusercontent.com/YenLiniOS/KThy/refs/heads/main/Scripts/AlightMotion.js, requires-body=true, timeout=5, tag=Alight Motion

#!author= Mạnh Yên (Kthy) 💞
