# =============================
#!name= 🐾Wink Vip 2026 - Khổng Mạnh Yên🐣
#!desc= Mở Khoá tất cả chức năn VIP | Hỗ trợ Chỉnh ảnh vv.. | Yêu cầu bật bảo vệ QUIC ~ Đã Fix lỗi by Khổng Mạnh Yên 👑
#!tag=Unlock VIP Wink by Yên
#!author= Mạnh Yên (Kthy) 💞
# 💬 Web: https://beacons.ai/o.oyen  
# 🫆 Tạo bởi: Khổng Mạnh Yên 🐥
#!version= 2
# =============================
[General]
bypass-system = true
skip-proxy = *.local, *.crashlytics.com
tun-excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12

[MITM]
hostname = api.revenuecat.com, buy.itunes.apple.com, api-sub.meitu.com

[Script]
WinkVipCrack.js=type=http-response,pattern=^https?:\/\/api-sub\.meitu\.com\/v2\/user\/vip_info_by_group\.json,requires-body=1,script-path=https://raw.githubusercontent.com/YenLiniOS/KThy/refs/heads/main/Scripts/Wink.js
